version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ev_charger
      MYSQL_ROOT_PASSWORD: evchargehomeexam
    ports:
      - "3306:3306"
    volumes:
      - ./ev_charger.sql:/docker-entrypoint-initdb.d/ev_charger.sql
      - db-data:/var/lib/mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: evchargehomeexam

  reactapp:
    build:
      context: ./ev-charger-react
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nodejs:
    build:
      context: ./ev-charger-node 
      dockerfile: Dockerfile
    depends_on:
      - app

volumes:
  db-data: